"""
Export cross-stack parity fixtures (Phase 0 of the colour-science overhaul).

Writes schemestealer-react/tests/fixtures/parity.json containing:

  * conversions: hex -> CIELAB (D65) computed by the backend's canonical
    skimage path (core.colour_maths.rgb_to_lab). The frontend test asserts
    culori's `lab65` converter agrees — pinning the "one rgb->lab" invariant
    across the stack boundary.
  * deltas: LAB pairs -> CIEDE2000 computed by skimage. The frontend test
    asserts culori's differenceCiede2000 agrees on lab65-tagged inputs.

Re-run after changing any conversion code:

    cd python-api
    venv/Scripts/python scripts/export_parity_fixtures.py
"""

import json
import sys
from pathlib import Path

_PY_API = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PY_API))

from core.colour_maths import ciede2000_single, rgb_to_lab  # noqa: E402

OUT_PATH = (_PY_API.parent / "schemestealer-react" / "tests" / "fixtures"
            / "parity.json")
PAINTS_PATH = _PY_API / "paints_groundtruth.json"

# Hand-picked hexes spanning the gamut: primaries, secondaries, neutrals,
# near-neutrals, dark and pale extremes — the regions where conversion
# implementations typically drift.
SPAN_HEXES = [
    "#000000", "#ffffff", "#808080", "#0a0a0a", "#f5f5f5",
    "#ff0000", "#00ff00", "#0000ff", "#ffff00", "#00ffff", "#ff00ff",
    "#c0392b", "#27ae60", "#2980b9", "#8e44ad", "#f39c12",
    "#7f6a4f", "#1b2a4a", "#e8dcc8", "#3d0c11", "#94a3b8",
]

# Neutral-axis and boundary pairs (the CLAUDE.md discontinuity band) plus a
# spread of realistic paint-to-paint distances.
EXTREME_PAIRS = [
    ((0.0, 0.0, 0.0), (100.0, 0.0, 0.0)),
    ((50.0, 0.0, 0.0), (50.0, 0.5, -0.5)),
    ((0.0, 0.01, -0.01), (1.0, 0.0, 0.0)),
    ((99.0, 0.0, 0.0), (100.0, -0.01, 0.01)),
    ((50.0, 2.6772, -79.7751), (50.0, 0.0, -82.7485)),   # Sharma pair 1
    ((50.0, -1.3802, -84.2814), (50.0, 0.0, -82.7485)),  # Sharma pair 3
]


def _hex_to_lab(hex_str: str):
    h = hex_str.lstrip("#")
    rgb = [int(h[i:i + 2], 16) for i in (0, 2, 4)]
    return rgb_to_lab(rgb)


def main() -> None:
    paints = json.loads(PAINTS_PATH.read_text(encoding="utf-8"))

    # Every 40th paint's chart hex exercises real product colours.
    sampled = paints[::40]

    conversions = [{"hex": hx, "lab": _hex_to_lab(hx)} for hx in SPAN_HEXES]
    conversions += [{"hex": p["hex"], "lab": _hex_to_lab(p["hex"])}
                    for p in sampled]

    deltas = [{"lab1": list(a), "lab2": list(b),
               "de": ciede2000_single(a, b)}
              for a, b in EXTREME_PAIRS]
    # Consecutive sampled paints give realistic small/medium distances.
    labs = [p["lab"] for p in sampled if p.get("lab")]
    deltas += [{"lab1": list(a), "lab2": list(b),
                "de": ciede2000_single(a, b)}
               for a, b in zip(labs, labs[1:])]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps({
        "note": "Generated by python-api/scripts/export_parity_fixtures.py — "
                "backend skimage values are the ground truth. Regenerate "
                "after any conversion change.",
        "conversions": conversions,
        "deltas": deltas,
    }, indent=1), encoding="utf-8")
    print(f"wrote {OUT_PATH} "
          f"({len(conversions)} conversions, {len(deltas)} delta pairs)")


if __name__ == "__main__":
    main()
