/**
 * DEC-8, the offline half — the offline wash slot must not publish a match score.
 *
 * The backend half of this commit stops `services/recipe_builder.py` scoring the
 * wash paint's own hex against the card colour: a wash is chosen by family
 * archetype (`WashMapping`, white -> 'dark'), never by colour, so the number was
 * a category error under a field name the base slot uses for a real CIEDE2000
 * match distance.
 *
 * Offline the same field was worse, because it was not even a measurement.
 * `washForFamily` returned a LITERAL `deltaE: 0` — the wash comes pre-resolved
 * from `lib/washMapping.ts` (generated by `scripts/build_wash_mapping.py`), so
 * there is no distance to report and none was ever computed. Zero was a
 * placeholder that read as a perfect match.
 *
 * WHY IT WAS USER-VISIBLE, which the DEC-8 brief had the other way round:
 *
 *   1. `PaintRecipeCard.tsx:632` computes
 *      `isPerfectMatch = activePaint.deltaE !== undefined && activePaint.deltaE < 3`
 *      and — unlike the ΔE badge at `:673`, which is gated to the base slot by
 *      `shouldShowDeltaBadge` — it is NOT gated on `step.key`. So a "✓ Perfect"
 *      chip rendered on EVERY offline wash row, on every scan, driven by a
 *      hardcoded 0. Online it never fired: measured over 198 served wash slots
 *      the minimum was 5.1, so 0 of 198 were under 3.
 *   2. `lib/clipboard.ts:75` prints `ΔE {n}` for every slot carrying the field,
 *      and `PaintRecipeCard.tsx:259` builds that slot array over all four
 *      RECIPE_STEPS including wash. The copy-recipe export therefore published
 *      the wash number as text the user pastes in public — `ΔE 0.0` offline, and
 *      online a real number that reached 76.6.
 *
 * This does not hide a ΔE (invariant 10). Nothing was measured to hide.
 */

import { describe, it, expect } from 'vitest';
import { getRecipeForColor } from '../paintMatcher';

describe('DEC-8 — the offline wash carries no match score', () => {
  it('omits deltaE on the wash slot for every brand', () => {
    // Three unrelated families, so this is not one lucky lookup in washMapping.
    const cases: Array<[[number, number, number], string]> = [
      [[95, 0, 0], 'white'],
      [[32, 53, 37], 'red'],
      [[50, 0, 0], 'grey'],
    ];
    const brands = ['citadel', 'vallejo', 'army-painter'] as const;

    for (const [lab, family] of cases) {
      for (const brand of brands) {
        const wash = getRecipeForColor(lab, family, brand).wash;
        expect(wash, `no offline wash resolved for ${family}/${brand}`).not.toBeNull();
        // FAILS IF: washForFamily reinstates `deltaE: 0` (or any value). Fails
        // before this commit on all nine combinations.
        expect(
          wash!.deltaE,
          `${family}/${brand} wash published deltaE ${wash!.deltaE}`
        ).toBeUndefined();
      }
    }
  });

  it('still resolves a real named wash — the field went, the recommendation did not', () => {
    // FAILS IF: the fix removed the wash slot rather than its score. That is the
    // most likely way to over-apply this commit, and it would silently drop a
    // quarter of every offline recipe.
    const wash = getRecipeForColor([95, 0, 0], 'white', 'citadel').wash;
    expect(wash).not.toBeNull();
    expect(wash!.name.length).toBeGreaterThan(0);
    expect(wash!.hex).toMatch(/^#[0-9a-fA-F]{6}$/);
    expect(wash!.type).toBe('wash');
  });

  it('leaves base, highlight and shade scores alone', () => {
    // The counterpart guard: only the wash is a category error. base/highlight/
    // shade are genuine distances from a colour the user can reason about, and
    // the base slot's is the one the badge shows.
    //
    // FAILS IF: deltaE is stripped from `findClosestPaint` instead of from
    // `washForFamily` — which would take the base badge with it.
    const recipe = getRecipeForColor([32, 53, 37], 'red', 'citadel');
    for (const slot of ['base', 'highlight', 'shade'] as const) {
      expect(recipe[slot], `${slot} slot vanished`).not.toBeNull();
      expect(
        typeof recipe[slot]!.deltaE,
        `${slot} slot lost its match score`
      ).toBe('number');
    }
  });
});
