/**
 * Cross-stack colour parity tests (Phase 0 of the colour-science overhaul).
 *
 * The architecture's "one rgb→lab, one ΔE" invariant spans a language
 * boundary: the backend uses skimage (D65), the frontend uses culori. These
 * tests pin the two stacks together against a fixture generated by the
 * backend (tests/fixtures/parity.json — regenerate with
 * python-api/scripts/export_parity_fixtures.py after any conversion change).
 *
 * Calibrated tolerances: culori lab65 and skimage agree to ~0.012 per LAB
 * channel (white-point constant rounding); their CIEDE2000 implementations
 * agree to machine precision on identical inputs. A tolerance breach means a
 * real divergence (e.g. someone reintroducing culori's D50 'lab' mode for
 * DB values — audit finding F9).
 */

import { describe, it, expect } from 'vitest';
import { converter, differenceCiede2000 } from 'culori';
import { deltaE2000 } from '../lib/deltaE';
import fixture from './fixtures/parity.json';

const toLab65 = converter('lab65');
const deltaE = differenceCiede2000();

describe('hex → CIELAB(D65) conversion parity (culori lab65 vs backend skimage)', () => {
  it.each(fixture.conversions.map(c => [c.hex, c.lab] as const))(
    '%s converts within 0.05 per channel',
    (hex, backendLab) => {
      const lab = toLab65(hex);
      expect(lab).toBeDefined();
      expect(Math.abs(lab!.l - backendLab[0])).toBeLessThan(0.05);
      expect(Math.abs((lab!.a ?? 0) - backendLab[1])).toBeLessThan(0.05);
      expect(Math.abs((lab!.b ?? 0) - backendLab[2])).toBeLessThan(0.05);
    },
  );
});

describe('CIEDE2000 parity (culori vs backend skimage)', () => {
  it.each(fixture.deltas.map((d, i) => [i, d] as const))(
    'pair %i agrees within 1e-9',
    (_i, pair) => {
      const got = deltaE(
        { mode: 'lab65', l: pair.lab1[0], a: pair.lab1[1], b: pair.lab1[2] } as any,
        { mode: 'lab65', l: pair.lab2[0], a: pair.lab2[1], b: pair.lab2[2] } as any,
      );
      expect(Math.abs(got - pair.de)).toBeLessThan(1e-9);
    },
  );
});

describe('lib/deltaE adapter parity (the offline-detection ΔE path)', () => {
  it.each(fixture.deltas.map((d, i) => [i, d] as const))(
    'pair %i agrees with the backend within 1e-9',
    (_i, pair) => {
      const got = deltaE2000(
        { l: pair.lab1[0], a: pair.lab1[1], b: pair.lab1[2] },
        { l: pair.lab2[0], a: pair.lab2[1], b: pair.lab2[2] },
      );
      expect(Math.abs(got - pair.de)).toBeLessThan(1e-9);
    },
  );
});
