// Read-only access to schemestealer-react/lib/data/*.json. The factory NEVER writes
// these — it only consumes the shipped, generated data (invariant: generated files are
// regenerated by their own scripts, never hand-edited or written from here).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = resolve(HERE, '../../../schemestealer-react/lib/data');

function readJson<T>(name: string): T {
  return JSON.parse(readFileSync(resolve(DATA_DIR, name), 'utf-8')) as T;
}

// ---- paints_groundtruth.json -------------------------------------------------
export interface Paint {
  paint_id: string;
  name: string;
  brand: string;
  range: string;
  hex: string;
  lab: [number, number, number];
  color_family: string;
  category: string;
  finish: string;
  opacity_rating: number;
  swatch_spread: number;
  color_source: string;
}

// ---- conversions.json --------------------------------------------------------
export interface ConversionMatch {
  paint_id: string;
  name: string;
  hex: string;
  slug: string;
  delta_e: number;
  band: string;
}
export interface ConversionEntry {
  source: { name: string; brand: string; hex: string; paint_id: string };
  matches: Record<string, ConversionMatch[]>;
}
interface ConversionsFile {
  generated_at: string;
  paints: Record<string, ConversionEntry>;
}

// ---- daily_puzzles.json ------------------------------------------------------
interface DailyPuzzlesFile {
  salt_version: string;
  familyAdjacency: Record<string, string[]>;
  days: Record<string, { answer: string }>;
}

// ---- proof_schemes.json ------------------------------------------------------
export interface ProofScheme {
  id: string;
  model: string;
  originalPalette: string[]; // paint_ids (official, pricier)
  budgetPalette: string[]; // paint_ids (cheaper equivalents, index-aligned)
}

let _paints: Paint[] | null = null;
let _paintsById: Map<string, Paint> | null = null;
let _conversions: ConversionsFile | null = null;
let _puzzles: DailyPuzzlesFile | null = null;
let _schemes: ProofScheme[] | null = null;

export function paints(): Paint[] {
  if (!_paints) _paints = readJson<Paint[]>('paints_groundtruth.json');
  return _paints;
}

export function paintById(id: string): Paint | undefined {
  if (!_paintsById) _paintsById = new Map(paints().map((p) => [p.paint_id, p]));
  return _paintsById.get(id);
}

export function conversions(): ConversionsFile {
  if (!_conversions) _conversions = readJson<ConversionsFile>('conversions.json');
  return _conversions;
}

export function dailyPuzzles(): DailyPuzzlesFile {
  if (!_puzzles) _puzzles = readJson<DailyPuzzlesFile>('daily_puzzles.json');
  return _puzzles;
}

export function proofSchemes(): ProofScheme[] {
  if (!_schemes) _schemes = readJson<ProofScheme[]>('proof_schemes.json');
  return _schemes;
}
