/**
 * Clipboard utility functions for copying hex codes and paint data
 */

export interface CopyNotification {
  message: string;
  type: 'success' | 'error';
}

/**
 * Copy single hex code to clipboard
 */
export async function copyHexCode(hex: string): Promise<CopyNotification> {
  try {
    await navigator.clipboard.writeText(hex);
    return {
      message: `Copied ${hex}`,
      type: 'success',
    };
  } catch (error) {
    return {
      message: 'Failed to copy',
      type: 'error',
    };
  }
}

/**
 * Copy all hex codes to clipboard (comma-separated)
 */
export async function copyAllHexCodes(colors: Array<{ hex: string; name: string }>): Promise<CopyNotification> {
  try {
    const hexList = colors.map(c => c.hex).join(', ');
    await navigator.clipboard.writeText(hexList);
    return {
      message: `Copied ${colors.length} color codes`,
      type: 'success',
    };
  } catch (error) {
    return {
      message: 'Failed to copy',
      type: 'error',
    };
  }
}

/**
 * Copy formatted color list to clipboard
 */
export async function copyFormattedColors(
  colors: Array<{ hex: string; name: string; percentage: number }>
): Promise<CopyNotification> {
  try {
    const formatted = colors
      .map(c => `${c.name}: ${c.hex} (${c.percentage}%)`)
      .join('\n');

    await navigator.clipboard.writeText(formatted);
    return {
      message: `Copied formatted color list`,
      type: 'success',
    };
  } catch (error) {
    return {
      message: 'Failed to copy',
      type: 'error',
    };
  }
}

/**
 * Copy paint requisition list (for miniscan results)
 */
export async function copyPaintRequisition(
  paints: Array<{ name: string; brand: string; hex: string; deltaE?: number }>
): Promise<CopyNotification> {
  try {
    const header = '═══ SCHEMESTEALER PAINT REQUISITION ═══\n\n';
    const paintList = paints
      .map((p, i) => {
        const deltaE = p.deltaE !== undefined ? ` [ΔE: ${p.deltaE.toFixed(1)}]` : '';
        return `${i + 1}. ${p.brand} - ${p.name} (${p.hex})${deltaE}`;
      })
      .join('\n');
    const footer = '\n\nGenerated by SchemeStealer';

    const fullText = header + paintList + footer;
    await navigator.clipboard.writeText(fullText);

    return {
      message: `Copied ${paints.length} paint recommendations`,
      type: 'success',
    };
  } catch (error) {
    return {
      message: 'Failed to copy',
      type: 'error',
    };
  }
}

/**
 * Copy for Discord - formatted with markdown
 */
export async function copyForDiscord(data: {
  type: 'miniscan' | 'inspiration';
  colors: Array<{ hex: string; name: string; percentage?: number }>;
  paints?: Array<{ name: string; brand: string }>;
}): Promise<CopyNotification> {
  try {
    const title = data.type === 'miniscan'
      ? '**🎨 Miniature Color Analysis - SchemeStealer**'
      : '**✨ Color Palette Extraction - SchemeStealer**';

    const colorList = data.colors
      .map(c => {
        const percentage = c.percentage ? ` (${c.percentage}%)` : '';
        return `• \`${c.hex}\` ${c.name}${percentage}`;
      })
      .join('\n');

    let message = `${title}\n\n${colorList}`;

    if (data.paints && data.paints.length > 0) {
      const paintList = data.paints
        .slice(0, 5) // Top 5 recommendations
        .map(p => `• ${p.brand} - ${p.name}`)
        .join('\n');
      message += `\n\n**Recommended Paints:**\n${paintList}`;
    }

    message += '\n\n_Powered by SchemeStealer_';

    await navigator.clipboard.writeText(message);

    return {
      message: 'Copied Discord-formatted text',
      type: 'success',
    };
  } catch (error) {
    return {
      message: 'Failed to copy',
      type: 'error',
    };
  }
}
