/**
 * Paint Matcher - Matches colors to paints from multiple brands
 * Uses offline paint database to supplement API results
 * Now supports structured paint recipes with BASE/SHADE/HIGHLIGHT/WASH
 */

import type { Paint, PaintMatch, BrandRecipe, PaintRecipe, ScanResult } from './types';
import { getPaintDatabase, type PaintData } from './paintDatabase';
import { deltaE2000 } from './deltaE';
import { WASH_MAP } from './washMapping';

export interface MultiBrandMatches {
  citadel: Paint[];
  vallejo: Paint[];
  armyPainter: Paint[];
}


// DB type strings that belong to each offline role
const _DOMINANT_TYPES = new Set(['base', 'layer', 'air', 'contrast']);
const _SHADE_TYPES = new Set(['shade', 'contrast']);
const _WASH_TYPES = new Set(['shade', 'wash', 'ink']);

// Matches the backend TRANSPARENCY_PENALTY constant
const _TRANSPARENCY_PENALTY = 8.0;

/**
 * Get top N paint matches for a color from each brand.
 * Uses dominant role: Base/Layer/Air only, with transparency penalty on contrast paints.
 */
export function getMultiBrandMatches(
  colorLab: [number, number, number],
  matchesPerBrand: number = 3
): MultiBrandMatches {
  const paintDatabase = getPaintDatabase();

  // Group paints by brand, pre-filtered to dominant role types
  const citadelPaints = paintDatabase.filter(
    (p) => p.brand.toLowerCase() === 'citadel' && _DOMINANT_TYPES.has(p.type.toLowerCase())
  );
  const vallejoPaints = paintDatabase.filter(
    (p) => p.brand.toLowerCase() === 'vallejo' && _DOMINANT_TYPES.has(p.type.toLowerCase())
  );
  const armyPainterPaints = paintDatabase.filter(
    (p) => p.brand.toLowerCase() === 'army painter' && _DOMINANT_TYPES.has(p.type.toLowerCase())
  );

  // Find top matches for each brand with transparency penalty
  const citadelMatches = findTopMatches(colorLab, citadelPaints, matchesPerBrand, true);
  const vallejoMatches = findTopMatches(colorLab, vallejoPaints, matchesPerBrand, true);
  const armyPainterMatches = findTopMatches(colorLab, armyPainterPaints, matchesPerBrand, true);

  return {
    citadel: citadelMatches,
    vallejo: vallejoMatches,
    armyPainter: armyPainterMatches,
  };
}

/**
 * Find top N closest paint matches with optional transparency penalty.
 * applyTransparencyPenalty adds transparency * PENALTY to deltaE before sorting,
 * so highly transparent paints (contrast/inks) are deprioritised unless the colour
 * advantage is large enough to overcome the penalty.
 */
function findTopMatches(
  colorLab: [number, number, number],
  paints: PaintData[],
  limit: number,
  applyTransparencyPenalty: boolean = false
): Paint[] {
  // Calculate Delta-E (+ optional transparency penalty) for each paint
  const matches = paints.map((paint) => {
    const rawDeltaE = deltaE2000(
      { l: colorLab[0], a: colorLab[1], b: colorLab[2] },
      paint.lab
    );
    const penalty = applyTransparencyPenalty
      ? (paint.transparency ?? 0) * _TRANSPARENCY_PENALTY
      : 0;

    return {
      name: paint.name,
      brand: paint.brand,
      hex: paint.hex,
      type: paint.type,
      colorFamily: paint.colorFamily,  // display family from DB (matches backend)
      rgb: [paint.rgb.r, paint.rgb.g, paint.rgb.b] as [number, number, number],
      lab: [paint.lab.l, paint.lab.a, paint.lab.b] as [number, number, number],
      deltaE: Math.round(rawDeltaE * 10) / 10,  // true distance for display
      _sortKey: rawDeltaE + penalty,             // penalised key for ranking only
    };
  });

  // Sort by penalised key, expose true deltaE
  matches.sort((a, b) => a._sortKey - b._sortKey);
  return matches.slice(0, limit).map(({ _sortKey: _k, ...m }) => m);
}

/**
 * Adjust LAB lightness to generate highlight/shade variations
 */
function adjustLightness(
  lab: [number, number, number],
  delta: number
): [number, number, number] {
  return [Math.max(0, Math.min(100, lab[0] + delta)), lab[1], lab[2]];
}

/**
 * Offline wash for a colour family + brand, pre-resolved from the backend's wash
 * ladder (lib/washMapping.ts, generated by scripts/build_wash_mapping.py). Single
 * source of truth — no hand-maintained map and no fuzzy DB lookup, so the offline
 * fallback can't drift from the online wash logic.
 */
function washForFamily(
  family: string,
  brand: 'citadel' | 'vallejo' | 'army-painter'
): PaintMatch | null {
  const fam = (family || '').toLowerCase();
  const entry = WASH_MAP[fam]?.[brand] ?? WASH_MAP['default']?.[brand];
  if (!entry) return null;
  return { name: entry.name, hex: entry.hex, type: 'wash', deltaE: 0 };
}

/**
 * Generate a structured paint recipe for a color
 */
export function getRecipeForColor(
  colorLab: [number, number, number],
  colorFamily: string,
  brand: 'citadel' | 'vallejo' | 'army-painter'
): BrandRecipe {
  const paintDatabase = getPaintDatabase();
  const brandName = brand.replace('-', ' ');

  // Filter paints by brand
  const brandPaints = paintDatabase.filter(
    (p) => p.brand.toLowerCase() === brandName.toLowerCase()
  );

  // Filter for dominant-role paints (base/layer/air — no washes or contrasts)
  const basePaints = brandPaints.filter(
    (p) => _DOMINANT_TYPES.has(p.type.toLowerCase())
  );

  // Find best base match
  const baseMatch = findClosestPaint(colorLab, basePaints);

  // NOTE: the backend recipe graph (curated official chains + LAB-geometry
  // fallback) is authoritative for recipes. This client-side generator is a
  // simple lightness-shift fallback only and is not on a primary path. Deltas
  // are aligned to the backend's ideal dL* (±12) so the two don't diverge.
  // Monotonicity guard (mirrors backend recipe_geometry.derive_partner): a
  // highlight must be strictly lighter than the base colour, a shade strictly
  // darker. If no paint satisfies it we return null (honest empty) rather than a
  // wrong-direction match.
  const baseL = colorLab[0];
  const highlightLab = adjustLightness(colorLab, 12);
  const highlightMatch = findClosestPaint(highlightLab, basePaints, (p) => p.lab.l > baseL);

  const shadeLab = adjustLightness(colorLab, -12);
  const shadeMatch = findClosestPaint(shadeLab, basePaints, (p) => p.lab.l < baseL);

  // Wash from the backend-derived map (single source of truth).
  const washMatch = washForFamily(colorFamily, brand);

  return {
    base: baseMatch,
    shade: shadeMatch,
    highlight: highlightMatch,
    wash: washMatch,
  };
}

/**
 * Find closest paint match from a list
 */
function findClosestPaint(
  colorLab: [number, number, number],
  paints: PaintData[],
  filter?: (p: PaintData) => boolean
): PaintMatch | null {
  const pool = filter ? paints.filter(filter) : paints;
  if (pool.length === 0) return null;

  let bestMatch: PaintData | null = null;
  let bestDeltaE = Infinity;

  for (const paint of pool) {
    const dE = deltaE2000({ l: colorLab[0], a: colorLab[1], b: colorLab[2] }, paint.lab);

    if (dE < bestDeltaE) {
      bestDeltaE = dE;
      bestMatch = paint;
    }
  }

  if (!bestMatch) return null;

  return {
    name: bestMatch.name,
    hex: bestMatch.hex,
    type: bestMatch.type || 'paint',
    deltaE: Math.round(bestDeltaE * 10) / 10,
  };
}

/**
 * Generate full paint recipe for all brands
 */
export function getFullPaintRecipe(
  colorLab: [number, number, number],
  colorFamily: string
): PaintRecipe {
  // Scale75 dropped (Prompt 8): no measured ground truth, so it is not a
  // supported brand. Offline mode mirrors the online supported-brand set.
  return {
    citadel: getRecipeForColor(colorLab, colorFamily, 'citadel'),
    vallejo: getRecipeForColor(colorLab, colorFamily, 'vallejo'),
    army_painter: getRecipeForColor(colorLab, colorFamily, 'army-painter'),
  };
}

/**
 * Enhance scan result with multi-brand matches (legacy format — offline mode only).
 * In online mode the backend's results are used as-is.
 */
export function enhanceWithMultiBrandMatches(
  scanResult: ScanResult,
  matchesPerBrand: number = 3
): ScanResult {
  // Already has multi-brand matches — return unchanged.
  if (scanResult.detectedColors[0]?.paintMatches?.citadel) {
    return scanResult;
  }

  const detectedColors = scanResult.detectedColors.map((colour) => {
    const matches = getMultiBrandMatches(colour.lab, matchesPerBrand);
    return { ...colour, paintMatches: matches };
  });

  return { ...scanResult, detectedColors };
}

/**
 * Enhance scan result with structured paint recipes (new format — offline mode only).
 */
export function enhanceWithPaintRecipes(scanResult: ScanResult): ScanResult {
  // Already has recipes — return unchanged.
  if (scanResult.detectedColors[0]?.paintRecipe) {
    return scanResult;
  }

  const detectedColors = scanResult.detectedColors.map((colour) => {
    const recipe = getFullPaintRecipe(colour.lab, colour.family ?? 'Unknown');
    return { ...colour, paintRecipe: recipe };
  });

  return { ...scanResult, detectedColors };
}

/**
 * Search paints by display name OR alias (Prompt 2.6 — Task 6).
 *
 * Aliases carry old product names so customers with OLD pots can still find a
 * paint: Army Painter's pre-Fanatic Warpaints names, and Citadel display names.
 * The alias data lives on each `PaintData.aliases` (generated into
 * paintDatabase.ts) and is also served verbatim by the backend `/api/paints`
 * endpoint, which returns the full paints_groundtruth.json (every record
 * includes `aliases`). The canonical `alias → paint_id` map is emitted alongside the DB
 * build at `python-api/scripts/sources/name_aliases.json`.
 *
 * This is the single consumption point for client-side alias search; Prompt 6's
 * "tap the correct paint" UI builds on it.
 */
export function findPaintsByNameOrAlias(query: string): PaintData[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return getPaintDatabase().filter((p) => {
    if (p.name.toLowerCase().includes(q)) return true;
    return (p.aliases || []).some((a) => a.toLowerCase().includes(q));
  });
}
